courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('signup', views.user_signup, name='signup'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('contact-us', views.ContactUs.as_view(), name='contact-us'),
    path('thanks', views.thanks, name='thanks'),
    path('profile', views.profile_view, name='profile-view'),
    path('panel', views.panel, name='panel'),
    path('profile/<int:pk>/settings', views.ProfileSettings.as_view(), name='profile-settings'),
    path('panel/add_course', views.AddCourse.as_view(), name='add-course'),
    path('panel/courses', views.CourseList.as_view(), name='courses'),
    path('teacher_search/', views.TeacherSearch.as_view(), name='teacher_search'),
]

university/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.contrib.auth.models import User


class Course(models.Model):
    department = models.CharField(max_length=50, null=False, blank=False)
    name = models.CharField(max_length=50, null=False, blank=False)
    course_number = models.IntegerField(null=False)
    group_number = models.IntegerField(null=False)
    teacher_name = models.CharField(max_length=50, null=False, blank=False)
    start_time = models.TimeField(null=False)
    end_time = models.TimeField(null=False)
    DAYS = ((0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Thursday'))
    first_day = models.IntegerField(choices=DAYS, null=False)
    second_day = models.IntegerField(choices=DAYS, null=True, blank=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    gender = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female')))
    image = models.ImageField(upload_to='upload/')
    user_type = models.CharField(max_length=1, choices=(('S', 'Student'), ('T', 'Teacher')), null=True)

courses/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.mail import send_mail


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    error_messages = {
        'password_mismatch': 'Password and repeat password are not the same!'
    }

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']
        error_messages = {
            'username': {
                'unique': 'Your username is exists in system!'
            }
        }


class ContactUsForm(forms.Form):
    title = forms.CharField(required=True)
    text = forms.CharField(required=True, widget=forms.Textarea, max_length=250, min_length=10)
    email = forms.EmailField(required=True)

    def send_mail(self):
        send_mail(self.cleaned_data.get('title'),
                  f'{self.cleaned_data.get("text")} \n {self.cleaned_data.get("email")}', 'aghs8055@gmail.com',
                  ['aghs8055@gmail.com'], fail_silently=False)


class ProfileSettingsForm(forms.Form):
    first_name = forms.CharField(max_length=150, required=False)
    last_name = forms.CharField(max_length=150, required=False)
    image = forms.ImageField(required=False)
    bio = forms.CharField(widget=forms.Textarea, required=False)
    gender = forms.ChoiceField(choices=(('', '-----'), ('M', 'Male'), ('F', 'Female')), required=False)
    user_type = forms.ChoiceField(choices=(('', '-----'), ('S', 'Student'), ('T', 'Teacher')), required=False)

courses/views.py
import markdown
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from .forms import UserRegistrationForm, ContactUsForm, ProfileSettingsForm
from django.views.generic import FormView, CreateView, ListView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Course, Profile
from django import forms
from django.db.models import Q


def homepage(request):
    return HttpResponse(render(request, 'courses/homepage.html'))


def create_user(data):
    username, email = data['username'], data['email']
    first_name, last_name = data['first_name'], data['last_name']
    user = User(username=username, email=email, first_name=first_name, last_name=last_name)
    user.set_password(data['password'])
    user.save()
    return user


def user_signup(request):
    if request.method == 'GET':
        form = UserRegistrationForm()
        return HttpResponse(render(request, 'courses/register.html', context={'form': form}))
    elif request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if not form.is_valid():
            return HttpResponse(
                render(request, 'courses/register.html', context={'form': form}))

        user = form.save()
        profile = Profile.objects.create(user=user)
        user.profile = profile
        user.save()
        return HttpResponseRedirect(reverse('courses:homepage'))


def user_login(request):
    if request.method == 'GET':
        return HttpResponse(render(request, 'courses/login.html'))
    if request.method == 'POST':
        username, password = request.POST.get('username'), request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('courses:homepage'))
        else:
            return HttpResponse(
                render(request, 'courses/login.html', context={'error_message': 'Invalid Username or password'}))


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('courses:homepage'))


class ContactUs(FormView):
    template_name = 'courses/contact-us.html'
    form_class = ContactUsForm
    success_url = '/thanks'

    def form_valid(self, form):
        form.send_mail()
        return super(ContactUs, self).form_valid(form)


def thanks(request):
    return HttpResponse(render(request, 'courses/thanks.html'))


@login_required()
def profile_view(request):
    return HttpResponse(render(request, 'courses/profile_view.html'))


@login_required()
def panel(request):
    return HttpResponse(render(request, 'courses/panel.html'))


class ProfileSettings(LoginRequiredMixin, FormView):
    template_name = 'courses/profile_settings.html'
    form_class = ProfileSettingsForm
    success_url = '/profile'

    def form_valid(self, form):
        first_name, last_name = form.cleaned_data.get('first_name', ''), form.cleaned_data.get('last_name', '')
        if first_name != '':
            self.request.user.first_name = first_name
        if last_name != '':
            self.request.user.last_name = last_name
        self.request.user.profile.image = form.cleaned_data.get('image', None)
        self.request.user.profile.bio = markdown.markdown(form.cleaned_data.get('bio', None))
        self.request.user.profile.gender = form.cleaned_data.get('gender', None)
        self.request.user.profile.user_type = form.cleaned_data.get('user_type', None)
        self.request.user.save()
        self.request.user.profile.save()
        return super(ProfileSettings, self).form_valid(form)

    def get_form(self, form_class=None):
        form = super(ProfileSettings, self).get_form()
        form.initial['first_name'] = self.request.user.first_name
        form.initial['last_name'] = self.request.user.last_name
        form.initial['image'] = self.request.user.profile.image
        form.initial['bio'] = self.request.user.profile.bio
        form.initial['gender'] = self.request.user.profile.gender
        form.initial['user_type'] = self.request.user.profile.user_type
        return form


@method_decorator(staff_member_required, name='dispatch')
class AddCourse(CreateView):
    model = Course
    fields = '__all__'
    template_name = 'courses/add_course.html'
    success_url = '/panel'

    def get_form(self, form_class=None):
        form = super(AddCourse, self).get_form(form_class)
        form.fields['start_time'].widget = forms.TimeInput()
        form.fields['end_time'].widget = forms.TimeInput()
        return form


class CourseList(ListView):
    model = Course
    template_name = 'courses/courses.html'
    context_object_name = 'courses'
    paginate_by = 5


class TeacherSearch(ListView):
    model = User
    template_name = 'courses/teacher_search.html'
    context_object_name = 'teachers'

    def get_queryset(self):
        search = self.request.GET.get('search', '')
        queryset = User.objects.filter(profile__user_type='T')
        queryset = queryset.filter(
            Q(username__icontains=search) | Q(first_name__icontains=search) | Q(last_name__icontains=search))
        return queryset

courses/templates/courses/add_course.html
{% extends 'courses/base.html' %}
{% block title %}Course Creation{% endblock %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

courses/templates/courses/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'courses:homepage' %}">University</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'courses:homepage' %}">Homepage</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li>
                        <a class="nav-link active" aria-current="page" id="profile" href="{% url 'courses:profile-view' %}">Profile</a>
                    </li>
                    <li>
                        <a class="nav-link active" aria-current="page" id="panel" href="{% url 'courses:panel' %}">Panel</a>
                    </li>
                    <li>
                        <a class="nav-link active" aria-current="page" id="logout" href="{% url 'courses:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a class="nav-link active" aria-current="page" id="login" href="{%  url 'courses:login' %}">Login</a>
                    </li>
                    <li>
                        <a class="nav-link active" aria-current="page" id="register" href="{% url 'courses:signup' %}">Register</a>
                    </li>
                {% endif %}
                <li>
                    <a class="nav-link active" aria-current="page" id="contact-us" href="{% url 'courses:contact-us' %}">Contact Us</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'courses:teacher_search' %}" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

courses/templates/courses/contact-us.html
{% extends 'courses/base.html' %}
{% block title %}Contact Us{% endblock %}
{% block content %}
    <form method="post" action="{% url 'courses:contact-us' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>

{% endblock %}

courses/templates/courses/courses.html
{% extends 'courses/base.html' %}
{% block title %}Courses{% endblock %}
{% block content %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Department</th>
          <th scope="col">Days</th>
          <th scope="col">Time</th>
          <th scope="col">Teacher Name</th>
        </tr>
      </thead>
      <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.name }}</td>
                    <td>{{ course.department }}</td>
                    <td>
                        {{ course.get_first_day_display }}
                        {% if course.secondday %}
                            and {{ course.get_second_day_display }}
                        {% endif %}
                    </td>
                    <td>{{ course.start_time|date:"h:i" }} to {{ course.end_time|date:"h:i" }}</td>
                    <td>{{ course.teacher_name }}</td>
                </tr>
            {% endfor %}
      </tbody>
    </table>
{% endblock %}

courses/templates/courses/homepage.html
{% extends 'courses/base.html' %}
{% block title %}Homepage{% endblock %}
{% block content %}
    <h1>Hello. Welcome to university system.</h1>
{% endblock %}

courses/templates/courses/login.html
{% extends 'courses/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
    {% if error_message %}
        <ul>
            <li style="color:red">{{ error_message }}</li>
        </ul>
    {% endif %}
    <form method="post" action="{% url 'courses:login' %}">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" id="username">
        <br>
        <label for="password">Password:</label>
        <input type="password" name="password" id="password">
        <br>
        <input type="submit" value="Login">
    </form>
    <form method="get" action="{% url 'courses:signup' %}">
        {% csrf_token %}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

courses/templates/courses/panel.html
{% extends 'courses/base.html' %}
{% block title %}Panel{% endblock %}
{% block content %}
    {% if request.user.is_staff %}
        <a class="btn btn-primary" href="{% url 'courses:add-course' %}" role="button" id="make_new_course" href="{% url 'courses:add-course' %}">Add new Course</a><br><br>
    {% endif %}
    <a class="btn btn-primary" role="button" id="courses" href="{% url 'courses:courses' %}">Courses</a>
{% endblock %}

courses/templates/courses/profile_settings.html
{% extends 'courses/base.html' %}
{% block title %}Profile Settings{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

courses/templates/courses/profile_view.html
{% extends 'courses/base.html' %}
{% block title %}Profile View{% endblock %}
{% block content %}
    {% if request.user.profile.image %}
        <p><img src="{{ request.user.profile.image.url }}" width="250" height="250" class="rounded mx-auto d-block"></p>
    {% endif %}
    {% if request.user.profile.bio %}
        Bio: {{ request.user.profile.bio | safe }}
    {% endif %}
    <p>First name: {{ request.user.first_name }}</p>
    <p>Last name: {{ request.user.last_name }}</p>
    <p>Gender: {{ request.user.profile.get_gender_display }}</p>
    <p>User Type: {{ request.user.profile.get_user_type_display }}</p>
    <p>Username: {{ request.user.username }}</p>
    <a class="btn btn-primary" role="button" href="{% url 'courses:profile-settings' request.user.id %}">Edit User</a>
{% endblock %}

courses/templates/courses/register.html
{% extends 'courses/base.html' %}
{% block title %}Signup{% endblock %}
{% block content %}
    {% if error_messages %}
        <ul>
        {% for error_message in error_messages %}
            <li style="color: red">error_message</li>
        {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'courses:signup' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

courses/templates/courses/teacher_search.html
{% extends 'courses/base.html' %}
{% block title %}Teacher Search Result{% endblock %}
{% block content %}
    <table class="table">
      <thead>
        <tr>
            <th scope="col">Username</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
        </tr>
      </thead>
      <tbody>
            {% for teacher in teachers %}
                <tr>
                    <td>{{ teacher.username }}</td>
                    <td>{{ teacher.first_name }}</td>
                    <td>{{ teacher.last_name }}</td>
                </tr>
            {% endfor %}
      </tbody>
    </table>
{% endblock %}

courses/templates/courses/thanks.html
{% extends 'courses/base.html' %}
{% block title %}Thanks{% endblock %}
{% block content %}
    <h2>Thank you. You request submitted.</h2>
{% endblock %}